name: ci_cd
on:
  push:
    branches:
    - master
jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: |
          Set-PSDebug -Trace 1
          $ErrorActionPreference = "Stop"
          node test
          npm version patch
          node transpile
          npx pkg .
      - run: echo "::set-output name=version::$(npm view markright version)"
        id: version
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{steps.version.outputs.version}}
          release_name: ${{steps.version.outputs.version}}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: markright-linux
          asset_name: markright-linux
          asset_content_type: application/octet-stream
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: markright-macos
          asset_name: markright-macos
          asset_content_type: application/octet-stream
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: markright-win.exe
          asset_name: markright-win.exe
          asset_content_type: application/octet-stream
      - run: |
          git add package.json
          git checkout -- .
          if git diff-index --quiet HEAD --; then
            exit
          fi

          git config --global user.email "tomas@hubelbauer.net"
          git config --global user.name "Tomas Hubelbauer"
          git commit -m "Bump version"
          git pull --rebase
          git push
